#!/bin/bash

echo "

    [bash, networking, system, text, process, other, vim, tmux, git, docker, k8, ansible, terraform, slurm]

    bash:
      addpath
      removepath x

    networking:
        ps
        top
        ping
        mtr
        traceroute
        dig
        airmon
        airodump
        iptables
        netstat

    system:
        nmon
        iostat
        sar
        vmstat

    text:
        awk
        sed
        grep
        sort
        uniq
        cat
        cut
        echo
        fmt
        tr
        nl
        egrep
        fgrep
        wc

    process:
        ps
        top
        htop
        atop
        lsof

     other:
        strace
        dtrace
        systemtap
        uname
        df
        history

    utils:
      newnote       [custom]
      mozilla       [custom]

    vim:
      vimfixcmds    [custom]
      govim         [custom]

    tmux:
      tmuxcmds      [custom]

    git:
      savegit      [custom]
      remotegit    [custom]
      dumpgit      [custom]
      getstash     [custom]

    docker:

    k8:
      kubeconfig   [custom]
      kubeswc      [custom]

    ansible:

    terraform:

    slurm:
"
