#!/bin/bash

USAGE="Usage: [-m stash message]"
# use options -c, -f
while getopts "m:" opt; do
    case ${opt} in
        m ) MESSAGE=$OPTARG ;;
        \? ) echo $USAGE && exit 1;; 
    esac
done

if [ -z $MESSAGE ]; then
    echo "No command name specified."
    exit 1
fi

BRANCH=`git branch | grep "*"`
git stash save "$(date) - $BRANCH - $MESSAGE"
# add optional -b: git branch | grep \* | cut -d ' ' -f2
