#!/bin/bash

# SESSIONS > WINDOWS > PANES
SAVE='
-----SAVE-----\n
\n
Save:    C-a C-s\n
Restore: C-a C-r\n
'
OPEN='
-----OPEN-----\n
\n
https://github.com/tmux-plugins/tmux-open\n
https://vimeo.com/102455265
\n
\n
While in copy mode:\n
\n

Open Highlighted Section with Editor:                         ctrl-O\n
Open Highlighted Section with the system default program:     o\n
Search highlighted selection directly inside a search engine: Shift-s
\n
'
COPYCAT='"
-----COPYCAT-----\n
\n
https://github.com/tmux-plugins/tmux-copycat\n
\n

Simple File Search:  ctrl-b + ctrl f\n
URL Search:          ctrl-b + ctrl u\n
Number Search:       ctrl-b + ctrl d\n
'
SENSIBLE='
-----Sensible-----\n
\n
https://github.com/tmux-plugins/tmux-sensible \n'

RESURRECT='
-----Resurrect----\n
\n
https://github.com/tmux-plugins/tmux-resurrect \n
\n
Save:    C-a save \n
Restore: C-r \n
'
YANK='
-----Yank-----\n
\n
https://github.com/tmux-plugins/tmux-yank\n
https://vimeo.com/102039099
\n\n
Copy Command Line:           C-y \n
Copy Pane Working Directory: C-Y \n ' CONTINUM='""'
SESSIONS='
-----Sessions-----\n
\n
List Sessions: tmux ls \n
Attach Session: tmux attach -t work \n
New Session: tmux new -s $NAME \n
New Session: C-a, :new \n
New Session: C-a, b \n
Kill Session: tmux kill-session -t $NAME \n
Rename Session: C-a, $ \n
Detach Session: C-a, d \n
Switch Sessions:
    C-a (          previous session \n
    C-a )          next session \n
    C-a L          ‘last’ (previously used) session \n
    C-a s          choose a session from a list \n
Switch Client:
    tmux switch-client ${MAME}
'
WINDOWS='
-----Windows-----\n
\n
Switching:\n
    C-a 1 ...      switch to window 1, ..., 9,\n
    C-a p          previous window \n
    C-a n          next window \n
    C-a l          last used window \n
    C-a w          choose window from a list \n
\n
New Window     C-a c \n
Last Window    C-a l \n
Next Window    C-a p \n
Close:         C-a c \n
New:           C-a n \n
Switch:        C-a ${WINDOWNUMBER} \n
List Windows:  C-a w \n
Kill Window:   C-a & \n
Find Window:   C-a f \n
Rename Window: C-a , \n
'
PANE='
-----Pane-----\n
\n
Vertical:     C-a "\n
Horizontal:   C-a %\n
Left:         C-a Left\n
Right:        C-a Righ\n
Up:           C-a Up\n
Down:         C-a Down\n
Next:         C-a o\n
Last:         C-a ;\n
Swap:         C-a; C-o\n
Previous:     C-a {\n
Next:         C-a }\n
Exit:         C-a x\n
PaneToWindow: C-a !\n
NextPaneVim:  C-a h,j,k,l \n
Resize:       C-a resize the panes \n
ShowPane#:    C-a arrow keys \n

TO_LEARN:
    Syncing Panes: https://sanctum.geek.nz/arabesque/sync-tmux-panes/ setw synchronize-panes
'
HELP='-o [RES, SESSIONS, WINDOWS, PANES, YANK, SENSIBLE, COPYCAT, COPY, OPEN]'
USAGE="Usage: [-option commands for tmux object -a RES, SESSIONS, WINDOWS, PANES, YANK, SENSIBLE, COPYCAT, OPEN]" # use options -o n -d H
while getopts "o:h" opt; do
    case ${opt} in
        o ) OPT=$OPTARG ;;
        h ) P="NONEMPTY";;
        \? ) echo $USAGE && exit 1;;
    esac
done

clear
if [ "$OPT" != "" ]; then
    case $OPT in
        RES)
           echo -e ${RESURRECT};;
        SESSIONS)
           echo -e ${SESSIONS} ;;
        WINDOWS)
            echo -e ${WINDOWS} ;;
        PANES)
            echo -e ${PANE} ;;
        YANK)
            echo -e ${YANK} ;;
        SENSIBLE)
            echo -e ${SENSIBLE} ;;
        COPYCAT)
            echo -e ${COPYCAT} ;;
        OPEN)
            echo -e ${OPEN} ;;
        SAVE)
            echo -e ${SAVE} ;;
    esac
fi

if [[ "$P" ]]; then
    clear
    echo ${HELP}
    exit 0
fi
# TO LEARN
#https://www.bugsnag.com/blog/tmux-and-vi://www.bugsnag.com/blog/tmux-and-vim
